# Используем официальный OpenJDK 21 slim образ в качестве базового
FROM openjdk:21-slim

# Устанавливаем переменную среды GREETING
ENV GREETING=Welcome

# Копируем JAR файл Spring Boot приложения в контейнер
COPY target/docker-demo-0.0.1-SNAPSHOT.jar app.jar

# Указываем, что контейнер будет слушать на порту 8080
EXPOSE 8080

# Запускаем приложение
ENTRYPOINT ["java", "-jar", "app.jar"]
